src/objects/GoogleDriveConnector__c.object
<CustomObject>
    <description>This object serves as an integration connector to the Google Drive API. It contains a reference to a Google Drive Connector Type that is used to obtain tokens. This object stores information about the access and refresh tokens.</description>
    <fields>
        <fullName>AccessTokenExpiry__c</fullName>
        <label>Access Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AccessTokenRequested__c</fullName>
        <label>Access Token Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleDriveConnectorType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Google Drive Connector Type</label>
        <referenceTo>GoogleDriveConnectorType__c</referenceTo>
        <relationshipLabel>Google Drive Connectors</relationshipLabel>
        <relationshipName>Google_Drive_Connectors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RefreshToken__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector</label>
    <nameField>
        <label>Google Drive Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleDriveConnectorType__c.object
<CustomObject>
    <description>This object stores the configuration used in requesting and storing Google client ID credentials.</description>
    <fields>
        <fullName>AuthorizationEndpoint__c</fullName>
        <label>Authorization Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectUri__c</fullName>
        <label>Redirect URI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenEndpoint__c</fullName>
        <label>Token Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector Type</label>
    <nameField>
        <label>Google Drive Connector Type	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GoogleDriveUtilsTest.cls
@isTest
private class GoogleDriveUtilsTest {

    static testMethod void getActiveOpportunityConfigurationTest() {
    }
    
	static testMethod void getConnectorServiceTestReturnNewGoogleDriveConnectorService() {
		GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
		type.Name = 'test';
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = '1234';
		connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.RefreshToken__c = '1234';

        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
		
		GoogleDriveConnectorService service = GoogleDriveUtils.getConnectorService('test');
		System.assertNotEquals(null, service);
    }
    
	static testMethod void getConnectorServiceExceptionTest() {
		GoogleDriveConnectorService service = GoogleDriveUtils.getConnectorService('does not exist');
		System.assertEquals(null, service);
    }

	static testMethod void getIsConnectorValidConnectorValidTest() {
		GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
		type.Name = 'test';
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = '1234';
		connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.RefreshToken__c = '1234';

        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
   		GoogleDriveConnectorService service = GoogleDriveUtils.getConnectorService('test');

		System.assert(GoogleDriveUtils.isConnectorValid(service));
    }
    
	static testMethod void getIsConnectorValidConnectorInvalidTest() {
		GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
		type.Name = 'test';
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = '1234';
		connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.RefreshToken__c = null;

        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
		
		GoogleDriveConnectorService service = GoogleDriveUtils.getConnectorService('test');
		System.assertEquals(false, GoogleDriveUtils.isConnectorValid(service));
    }
    
	static testMethod void getCreateFolderTest() {
		ffhttp_GoogleDriveFiles files = new ffhttp_GoogleDriveFiles(null);
		ffhttp_GoogleDriveModelParent parent = new ffhttp_GoogleDriveModelParent();
		String folderName = 'folderName';
		
		ffhttp_GoogleDriveModelFile folder = GoogleDriveUtils.createFolder(files, parent, folderName); 
		System.assertNotEquals(null, folder);
    }
    
	static testMethod void getGetFolderNotFoundTest() {
		ffhttp_GoogleDriveFiles files = new ffhttp_GoogleDriveFiles(null);
		String folderName = 'not found';
		
		ffhttp_GoogleDriveModelFile folder = GoogleDriveUtils.getFolder(files, null, folderName);
		System.assertEquals(null, folder);
    }
    
	static testMethod void getGetFolderFoundMoreThanOneTest() {
		ffhttp_GoogleDriveFiles files = new ffhttp_GoogleDriveFiles(null);
		String folderName = '>';
		
		ffhttp_GoogleDriveModelFile folder = GoogleDriveUtils.getFolder(files, null, folderName);
		System.assertNotEquals(null, folder);
    }

	static testMethod void getGetFolderFoundOneTest() {
		ffhttp_GoogleDriveFiles files = new ffhttp_GoogleDriveFiles(null);
		String folderName = '1';
		
		ffhttp_GoogleDriveModelFile folder = GoogleDriveUtils.getFolder(files, null, folderName);
		System.assertNotEquals(null, folder);
    }
    
}