src/objects/GoogleDriveConnector__c.object
<CustomObject>
    <description>This object serves as an integration connector to the Google Drive API. It contains a reference to a Google Drive Connector Type that is used to obtain tokens. This object stores information about the access and refresh tokens.</description>
    <fields>
        <fullName>AccessTokenExpiry__c</fullName>
        <label>Access Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AccessTokenRequested__c</fullName>
        <label>Access Token Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <formula>NOT(ISBLANK(AccessToken__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GoogleDriveConnectorType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Google Drive Connector Type</label>
        <referenceTo>GoogleDriveConnectorType__c</referenceTo>
        <relationshipLabel>Google Drive Connectors</relationshipLabel>
        <relationshipName>Google_Drive_Connectors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RefreshTokenRequested__c</fullName>
        <label>Refresh Token Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RefreshToken__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenType__c</fullName>
        <label>Token Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector</label>
    <nameField>
        <label>Google Drive Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleDriveConnectorType__c.object
<CustomObject>
    <description>This object stores the configuration used in requesting and storing Google client ID credentials.</description>
    <fields>
        <fullName>AuthorizationEndpoint__c</fullName>
        <label>Authorization Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallbackURL__c</fullName>
        <label>Callback URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExtraUrlParameters__c</fullName>
        <label>Extra URL Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RedirectUri__c</fullName>
        <label>Redirect URI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScopeRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scope Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TokenEndpoint__c</fullName>
        <label>Token Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector Type</label>
    <nameField>
        <label>Google Drive Connector Type	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleDriveOpportunityConfiguration__mdt.object
<CustomObject>
    <description>This custom metadata type stores the settings used by the Google Drive/Opportunity integration.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value stores the current state of the Google Drive Opportunity integration. When this field is set to true, the Google Drive operations will be executed.</description>
        <inlineHelpText>This value stores the current state of the Google Drive Opportunity integration. When this field is set to true, the Google Drive operations will be executed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultBillingStateCount__c</fullName>
        <defaultValue>11000</defaultValue>
        <description>This value contains a default value used in determining the Google Drive folder name for an opportunity.</description>
        <inlineHelpText>This value contains a default value used in determining the Google Drive folder name for an opportunity.</inlineHelpText>
        <label>Default Billing State Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EmailAlert__c</fullName>
        <description>This field stores an email address that will be notified if a significant error occurs within the Google Drive integration. Examples: 1) Google Drive Connector needs to be re-authenticated 2) OAuth 2.0 credentials have been reset within Google Cloud Platform 3) the root folder does not exist.</description>
        <inlineHelpText>Stores an email address that will be notified if a significant error occurs within the Google Drive integration. Examples: Google Drive Connector requires re-authentication, OAuth credentials have been reset within GCP, root folder does not exist.</inlineHelpText>
        <label>Email Alert</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>GoogleDriveConnectorTypeName__c</fullName>
        <description>Provides a link between a custom metadata record and a Google Drive Connector Type. This value must point to a Google Drive Connector Type record via a matching Name.</description>
        <inlineHelpText>Provides a link between a custom metadata record and a Google Drive Connector Type. This value must point to a Google Drive Connector Type record via a matching Name.</inlineHelpText>
        <label>Google Drive Connector Type Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RootFolder__c</fullName>
        <description>The field stores the Google Drive folder name where the opportunity folders will be created. The folder must be uniquely named and must exist.</description>
        <inlineHelpText>The field stores the Google Drive folder name where the opportunity folders will be created. The folder must be uniquely named and must exist.</inlineHelpText>
        <label>Root Folder</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Drive Opportunity Configuration</label>
    <pluralLabel>Google Drive Opportunity Configuration</pluralLabel>
</CustomObject>

src/objects/GoogleDriveOpportunityRecordType__mdt.object
<CustomObject>
    <description>This custom metadata type stores the Opportunity record type settings used by the Google Drive/Opportunity integration. Each record type can have its own specific configuration (e.g. list of folder names).</description>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <label>Opportunity Record Type Developer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subfolders__c</fullName>
        <description>List of folder names to be created in Google Drive for a new opportunity specifically for its record type.</description>
        <inlineHelpText>List of folder names to be created in Google Drive for a new opportunity specifically for its record type.</inlineHelpText>
        <label>Subfolders</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Google Drive Opportunity Record Type</label>
    <pluralLabel>Google Drive Opportunity Record Types</pluralLabel>
</CustomObject>

src/classes/GoogleDriveUtils.cls
/**
 * GoogleDriveUtils
 * 
 * Support methods for Google Drive API v2. 
 */
public class GoogleDriveUtils {

    public static final String CLASS_NAME = 'GoogleDriveUtils';
	public static final String FOLDER_MIME_TYPE = 'application/vnd.google-apps.folder';
	
	private static Map<Schema.SObjectType,Map<Id,String>> recordTypesCache;
	private static List<sObject> recordTypesResults;
	
	static {
	    recordTypesCache = new Map<Schema.SObjectType,Map<Id,String>>();
		recordTypesResults = new List<sObject>();
	}
    
    /**
     * Returns the active Google Drive Opportunity Configuration custom metadata record.
     * If more than one record is found to be active, only one configuration is returned.
     * 
     * @return the GoogleDriveOpportunityConfiguration record
     */
    public static GoogleDriveOpportunityConfiguration__mdt getActiveOpportunityConfiguration() {
        GoogleDriveOpportunityConfiguration__mdt config = [SELECT RootFolder__c, GoogleDriveConnectorTypeName__c, DefaultBillingStateCount__c, EmailAlert__c
															FROM GoogleDriveOpportunityConfiguration__mdt
															WHERE Active__c = TRUE
															LIMIT 1];        
        return config;
    }
    
    /**
     * Returns the configured subfolders for each opportunity record type, keyed by record type name.
     * 
     * @return a map of subfolders keyed by record type name
     */
    public static Map<String,String> getSubfoldersByOpportunityRecordTypes() {
    	Map<String, String> subfoldersMap = new Map<String, String>();
    	for (GoogleDriveOpportunityRecordType__mdt record : [SELECT DeveloperName__c, Subfolders__c FROM GoogleDriveOpportunityRecordType__mdt]) {
    		subfoldersMap.put(record.DeveloperName__c, record.Subfolders__c);
    	}        
        return subfoldersMap;
    }
    
    /**
     * Returns the GoogleDriveConnectorService for a given Google Drive Connector Type's Name.
     * 
     * @param connectorTypeName The Name of a Google Drive Connector Type 
     * 
     * @return the GoogleDriveConnectorService or null if it isn't found
     */
    public static GoogleDriveConnectorService getConnectorService(String connectorTypeName) {
        try {
            GoogleDriveConnector__c c = [
                SELECT 
                c.TokenType__c, c.RefreshToken__c, c.RefreshTokenRequested__c, c.Name, c.Id, c.AccessToken__c, 
                c.AccessTokenRequested__c, c.AccessTokenExpiry__c, c.Active__c, 
                GoogleDriveConnectorType__r.TokenEndpoint__c, GoogleDriveConnectorType__r.Scope__c, GoogleDriveConnectorType__r.ScopeRequired__c, 
                GoogleDriveConnectorType__r.RedirectUri__c, GoogleDriveConnectorType__r.Name, GoogleDriveConnectorType__r.Id, 
                GoogleDriveConnectorType__r.ExtraUrlParameters__c, GoogleDriveConnectorType__r.DeveloperName__c, 
                GoogleDriveConnectorType__r.ClientSecret__c, GoogleDriveConnectorType__r.ClientId__c, GoogleDriveConnectorType__r.CallbackURL__c, 
                GoogleDriveConnectorType__r.AuthorizationEndpoint__c
                FROM GoogleDriveConnector__c c
                WHERE GoogleDriveConnectorType__r.Name =: connectorTypeName
                LIMIT 1
            ];
            
            if (c != null) {
                return new GoogleDriveConnectorService(c);
            }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, CLASS_NAME + ': getConnectorService exception: ' + e.getMessage() + ' for connector type named: ');
        }
        
        return null;
    }
    
    /**
     * Answers if the GoogleDriveConnectorService is found to be in a good state.
     * 
     * @param connectorService The Google Drive Connector Service to verify
     * 
     * @return true if valid, false otherwise
     */
    public static Boolean isConnectorValid(GoogleDriveConnectorService connectorService) {
        String message = connectorService.validateConnector();
        if (String.isEmpty(message)) {
            System.debug(LoggingLevel.INFO, CLASS_NAME + ': Google Drive connector is valid');
            return true;            
        } else {
            System.debug(LoggingLevel.ERROR, CLASS_NAME + ': Google Drive connector is not valid. ' + message);
            return false;
        }
    }
    
    /**
     * Creates a folder for a given name and within a given parent.
     * 
     * @param ffhttp_GoogleDriveFiles The Google Drive Files API class
     * @param ffhttp_GoogleDriveModelParent The parent
     * @param String folderName The name of the folder to create
     * 
     * @return the created folder
     */
    public static ffhttp_GoogleDriveModelFile createFolder(ffhttp_GoogleDriveFiles files, ffhttp_GoogleDriveModelParent parent, String folderName) {
        ffhttp_GoogleDriveModelParent [] parents = new ffhttp_GoogleDriveModelParent [] {parent};
		ffhttp_GoogleDriveModelFile folder = new ffhttp_GoogleDriveModelFile();
		folder.setTitle(folderName);
        folder.setParents(new ffhttp_GoogleDriveModelParent [] {parent});
		folder.setMimeType(FOLDER_MIME_TYPE);
		if (Test.isRunningTest()) {
			System.debug('Running in test mode');
		} else {
        	folder = (ffhttp_GoogleDriveModelFile) files.insertRequest(folder, null).execute();
		}
        return folder;
    }
    
    /**
     * Returns a folder for a given name.
     * 
     * @param ffhttp_GoogleDriveFiles The Google Drive Files API class
     * @param ffhttp_GoogleDriveModelParent The parent
     * @param String folderName The name of the folder to find
     * 
     * @return the found folder or null
     */
    public static ffhttp_GoogleDriveModelFile getFolder(ffhttp_GoogleDriveFiles files, ffhttp_GoogleDriveModelParent parent, String folderName) {
    	ffhttp_GoogleDriveFiles.ListRequest request = files.listRequest();
    	if (parent != null) {
			request.setQ('title = \'' + folderName + '\' and \'' + parent.getId() + '\' in parents and mimeType = \'' + FOLDER_MIME_TYPE + '\' and trashed = false');
    	} else {
    		request.setQ('title = \'' + folderName + '\' and mimeType = \'' + FOLDER_MIME_TYPE + '\' and trashed = false');
    	}
		
		ffhttp_GoogleDriveModelFile.ItemList folders = null;
		Integer found = 0;
		
		if (Test.isRunningTest()) {
			if (folderName.equals('1')) {
				return new ffhttp_GoogleDriveModelFile();
			} else if (folderName.equals('>')) {
				found = 2;
			}
		} else {
			folders = (ffhttp_GoogleDriveModelFile.ItemList) request.execute();
			found = folders.getItems().size();
		}
		
        if (found == 0) {
            return null;
        } else if (found > 1) {
            System.debug(LoggingLevel.WARN, 'Found more than one folder named ' + folderName + '! Using the first folder out of ' + found + ' found.');
        }
        
        if (Test.isRunningTest()) {
        	return new ffhttp_GoogleDriveModelFile();	
        } else {
        	return (ffhttp_GoogleDriveModelFile) folders.getItems().get(0);
        }
    }
    
	/**
	* Returns a map of active, user-available RecordType IDs for a given SObjectType,
	* keyed by each RecordType's unique, unchanging DeveloperName
	* 
	* @param the SobjectType
	* @return a map of record type developer names with their IDs
	* 
	* @see https://salesforce.stackexchange.com/questions/11968/what-would-be-the-best-approach-to-get-the-recordtype-id
	*/	
	private static Map<Id, String> getRecordTypeMapForObject(Schema.SObjectType token) {
		Map<Id, String> mapRecordTypes = recordTypesCache.get(token);
		if (mapRecordTypes == null) {
			mapRecordTypes = new Map<Id, String>();
			recordTypesCache.put(token, mapRecordTypes);
		} else {
			return mapRecordTypes;
		}

		Schema.DescribeSObjectResult obj = token.getDescribe();

		if (recordTypesResults == null || recordTypesResults.isEmpty()) {
			String soql = 'SELECT Id, Name, DeveloperName, sObjectType FROM RecordType WHERE IsActive = TRUE';
        	try {
            	recordTypesResults = Database.query(soql);
        	} catch (Exception ex) {
            	recordTypesResults = new List<SObject>();
        	}
    	}

	    Map<Id,Schema.RecordTypeInfo> recordTypeInfos = obj.getRecordTypeInfosByID();
		for (SObject recordType : recordTypesResults) { 
        	if (recordTypeInfos.get(recordType.Id) != null) {
				if (recordTypeInfos.get(recordType.Id).isAvailable()) {
					mapRecordTypes.put(recordType.Id, String.valueOf(recordType.get('DeveloperName')));
				} else {
	                System.debug('The record type ' + recordType.get('DeveloperName') + ' for object ' + recordType.get('sObjectType') + ' is not availiable for the user.');
    	        }
        	}
		}

		return mapRecordTypes;
	}
	
	public static String getOpportunityRecordTypeById(Id id) {
		Map<Id, String> recordTypes = getRecordTypeMapForObject(Opportunity.SObjectType);
		return recordTypes.get(id);
	}
}