src/objects/GoogleDriveConnector__c.object
<CustomObject>
    <description>This object serves as an integration connector to the Google Drive API. It contains a reference to a Google Drive Connector Type that is used to obtain tokens. This object stores information about the access and refresh tokens.</description>
    <fields>
        <fullName>AccessTokenExpiry__c</fullName>
        <label>Access Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AccessTokenRequested__c</fullName>
        <label>Access Token Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleDriveConnectorType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Google Drive Connector Type</label>
        <referenceTo>GoogleDriveConnectorType__c</referenceTo>
        <relationshipLabel>Google Drive Connectors</relationshipLabel>
        <relationshipName>Google_Drive_Connectors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RefreshToken__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector</label>
    <nameField>
        <label>Google Drive Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleDriveConnectorType__c.object
<CustomObject>
    <description>This object stores the configuration used in requesting and storing Google client ID credentials.</description>
    <fields>
        <fullName>AuthorizationEndpoint__c</fullName>
        <label>Authorization Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RedirectUri__c</fullName>
        <label>Redirect URI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenEndpoint__c</fullName>
        <label>Token Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Drive Connector Type</label>
    <nameField>
        <label>Google Drive Connector Type	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GoogleDriveConnectorServiceTest.cls
@isTest
private class GoogleDriveConnectorServiceTest {
	
	static testMethod void retrieveConnectorNoConnectorSetTest() {
    	String connectorId = 'id';
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connectorId);
        service.connectorId = null;
    	System.assertEquals(null, service.retrieveConnector());
    }
    
	static testMethod void retrieveConnectorFoundConnectorSetTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	String connectorId = connector.Id;
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connectorId);
        
        GoogleDriveConnector__c c = service.retrieveConnector();
    	System.assertEquals(connectorId, c.Id);
    }

    static testMethod void validateConnectorNullConnectorTest() {
    	String connectorId = '123456789012345678';
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connectorId);
        service.connectorId = null;
    	System.assertEquals('No connector found.', service.validateConnector());
    }
    
	static testMethod void validateConnectorNullAccessTokenConnectorTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals('The connector ' + connector.Name + ' has not been authorized.', service.validateConnector());
    }
    
    static testMethod void accessTokenExpiredUnknownRequestTimeTest() {
		GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
        System.assertEquals(false, service.accessTokenExpired());
    }
    
    static testMethod void accessTokenExpiredHasRequestTimeTest() {
		GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
        System.assertEquals(true, service.accessTokenExpired());
    }

    static testMethod void getAccessTokenTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        String accessToken = 'abcd';
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = accessToken;
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(accessToken, service.getAccessToken());
    }
    
    
	static testMethod void getAccessTokenValidateConnectorNullTest() {
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService('');
        service.connectorId = null;
        
    	System.assertEquals(null, service.getAccessToken());
    }
    
	static testMethod void getAuthorizationEndpointTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.getAuthorizationEndpoint());
    }
    
	static testMethod void getTokenEndpointTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.getTokenEndpoint());
    }
    
	static testMethod void getClientIdTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.getClientId());
    }
    
	static testMethod void getClientSecretTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.getClientSecret());
    }
    
	static testMethod void getRedirectsUriTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.getRedirectUri());
    }
    
	static testMethod void getExtraUrlParametersTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals('', service.getExtraUrlParameters());
    }
    
    
	static testMethod void validateConnectorNullRefreshTokenTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = '1234';
		connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.RefreshToken__c = null;

        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals('The connector ' + connector.Name + ' needs to be reauthorized.', service.validateConnector());
    }
    
	static testMethod void validateConnectorExchangeCodeTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.AccessToken__c = '1234';
		connector.AccessTokenRequested__c = Date.today();
        connector.AccessTokenExpiry__c = 200;
        connector.RefreshToken__c = '1234';

        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	System.assertEquals(null, service.validateConnector());
    }
    
	static testMethod void exchangeCodeHasAuthCodeTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	service.exchangeCode('1234', true);
    }
    
	static testMethod void exchangeCodeNoAuthCodeTest() {
        GoogleDriveConnectorType__c type = new GoogleDriveConnectorType__c();
        type.AuthorizationEndpoint__c = 'authorizationEndpoint';
        type.ClientId__c = 'clientId';
        type.ClientSecret__c = 'clientSecret';
        type.RedirectUri__c = 'redirectUri';
        type.TokenEndpoint__c = 'tokenEndpoint';
        insert type;
        
        GoogleDriveConnector__c connector = new GoogleDriveConnector__c();
        connector.Name = 'Google Test';
        connector.GoogleDriveConnectorType__c = type.Id;
        insert connector;
        
    	GoogleDriveConnectorService service = new GoogleDriveConnectorService(connector);
    	service.exchangeCode('1234', false);
    }
}