src/objects/GoogleDriveLog__c.object
<CustomObject>
    <description>This custom object stores log records created during the Google Drive Opportunity integration.</description>
    <fields>
        <fullName>LogLevel__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <description>The date and time that the log entry was created.</description>
        <inlineHelpText>The date and time that the log entry was created.</inlineHelpText>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Google Drive Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Log Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Drive Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityGoogleDriveTriggerHandlerTest.cls
@isTest
private class OpportunityGoogleDriveTriggerHandlerTest {

	private static Integer BATCH_SIZE = 1;

    static testMethod void insertTest() {
    	
    	Test.startTest();
    	List<Opportunity> opportunities = newOpportunities();
    	insert opportunities;
    	Test.stopTest();
    	
    }
    
    static testMethod void handleMethodsTest() {
    	Test.startTest();
		OpportunityGoogleDriveTriggerHandler handler = new OpportunityGoogleDriveTriggerHandler();
		handler.handleBeforeInsert(null);
		
		handler.handleBeforeUpdate(null, null, null, null);
		handler.handleAfterUpdate(null, null, null, null);

		handler.handleBeforeDelete(null, null);
		handler.handleAfterDelete(null, null);		
    	
    	Test.stopTest();
    }
    
    static testMethod void getLogLevelTest() {
    	System.assertEquals('FATAL', OpportunityGoogleDriveTriggerHandler.getLogLevel(null));
    	System.assertEquals('ERROR', OpportunityGoogleDriveTriggerHandler.getLogLevel(LoggingLevel.ERROR));
    	System.assertEquals('WARN', OpportunityGoogleDriveTriggerHandler.getLogLevel(LoggingLevel.WARN));
    	System.assertEquals('INFO', OpportunityGoogleDriveTriggerHandler.getLogLevel(LoggingLevel.INFO));
    	System.assertEquals('DEBUG', OpportunityGoogleDriveTriggerHandler.getLogLevel(LoggingLevel.DEBUG));
    }
    
    static testMethod void logCalloutMessageTest() {
    	Test.startTest();
    	OpportunityGoogleDriveTriggerHandler.logCalloutMessage(null, 'test');
    	Test.stopTest();
    }
    
	static testMethod void logFolderNames() {
    	Test.startTest();
    	
    	List<GoogleDriveLog__c> logs = new List<GoogleDriveLog__c>();
    	GoogleDriveLog__c log = new GoogleDriveLog__c();
    	log.Message__c = 'message';
    	log.LogLevel__c = 'DEBUG';
    	log.Timestamp__c = Date.today();
    	logs.add(log);
    	
    	List<String> names = new List<String>();
    	names.add('Test');
    	
    	OpportunityGoogleDriveTriggerHandler.logFolderNames(logs, names, 'test');
    	Test.stopTest();
    }
    
	static testMethod void logFatalCalloutError() {
    	Test.startTest();
    	
    	List<GoogleDriveLog__c> logs = new List<GoogleDriveLog__c>();
    	GoogleDriveLog__c log = new GoogleDriveLog__c();
    	log.Message__c = 'message';
    	log.LogLevel__c = 'DEBUG';
    	log.Timestamp__c = Date.today();
    	logs.add(log);
    	
    	List<String> names = new List<String>();
    	names.add('Test');
    	
    	OpportunityGoogleDriveTriggerHandler.logFatalCalloutError(logs, names, 'message');
    	Test.stopTest();
    }

	static testMethod void composeMailTest() {		
    	System.assertEquals(null, OpportunityGoogleDriveTriggerHandler.composeMail(null, null));    	
    	System.assertNotEquals(null, OpportunityGoogleDriveTriggerHandler.composeMail('test@test.com', 'test'));
    }
    
	static testMethod void sendEmailAlertTest() {
		OpportunityGoogleDriveTriggerHandler.sendEmailAlert('test@test.com', 'test');
    }
    
    public static List<Opportunity> newOpportunities() {
    	List<Opportunity> opportunities = new List<Opportunity>();
    	for (Integer i = 1; i <= BATCH_SIZE; i++) {
    		Opportunity opportunity = new Opportunity();
    		opportunity.Name = 'Test ' + String.valueOf(i);
    		opportunity.Job_Num__c = 'AZ-11000';
    		opportunity.StageName = 'Prospecting';
    		opportunity.CloseDate = Date.today();
    		opportunities.add(opportunity);
    	}
    	return opportunities;
    }
}