src/objects/NoteSubject__c.object
<CustomObject>
    <description>Stores note subjects and objects with access to subject</description>
    <fields>
        <fullName>AllowedForAllObjects__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this for the Note Subject to be available to All Objects</inlineHelpText>
        <label>Allowed for All Objects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AllowedObjects__c</fullName>
        <description>Objects that have access to this Note Subject</description>
        <label>Allowed Objects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Note Subject</label>
    <nameField>
        <label>Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Note Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPremierNotes.cls
@isTest
public class TestPremierNotes {
    static testMethod void test1() {
        // cover constructor
        PremierNotes p = new PremierNotes();
        
        // create notesubjects to pull
        list<NoteSubject__c> testSubs = new list<NoteSubject__c>();
        testSubs.add(new NoteSubject__c(Name = 'test', AllowedObjects__c = 'Account'));
        testSubs.add(new NoteSubject__c(Name = 'another test', AllowedForAllObjects__c = true));
        insert testSubs;
        
        // create account for insert of note later
        Account a = new Account (Name = 'test', BillingState = 'Pennsylvania');
        insert a;
        
        // start tests
        test.startTest();
        
        // get notesubs for account, both above, plus the --None-- standard entry = 3
        list<String> testGetSubsOne = PremierNotes.getSubjects('Account');
        system.assert(testGetSubsOne.size() == 3);
        
        // only the allowedforallobjects=true from above plus the --None-- standard entry = 2
        list<String> testGetSubsTwo = PremierNotes.getSubjects('Contact');
        system.assert(testGetSubsTwo.size() == 2);
        
        // insert a note
        PremierNotes.takeInput(testGetSubsOne[1], 'test', a.Id);
        test.stopTest();
    }
}