src/objects/NoteSubject__c.object
<CustomObject>
    <description>Stores note subjects and objects with access to subject</description>
    <fields>
        <fullName>AllowedForAllObjects__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this for the Note Subject to be available to All Objects</inlineHelpText>
        <label>Allowed for All Objects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AllowedObjects__c</fullName>
        <description>Objects that have access to this Note Subject</description>
        <label>Allowed Objects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Note Subject</label>
    <nameField>
        <label>Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Note Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PremierNotes.cls
public with sharing class PremierNotes {
	
    // constructor
    public PremierNotes() {}
    
    // get pre-determined note subjects
    @AuraEnabled
	public static List<String> getSubjects(String objName) {
		
        // holds queried notesubject object, sort by name alphabetically
		List<NoteSubject__c> SubjectRecs = new List<NoteSubject__c>();
		SubjectRecs = [SELECT Id, Name FROM NoteSubject__c WHERE AllowedObjects__c INCLUDES (:objName) OR AllowedForAllObjects__c = true ORDER BY Name ASC];
		
        // list to return subject strings
        List<String> Subjects = new List<String>();
        
        // add in empty subject string, also helps in validation
        Subjects.add('--None--');
        for (NoteSubject__c n : SubjectRecs)
            Subjects.add(n.Name);
		
        return Subjects;
	}
    
    // take the input from the component
    @AuraEnabled
    public static void takeInput(String subj, String body, String recId) {
        system.debug('In takeInput: ' + subj + ' ' + body + ' ' + recId);
        
        Core.CreateNote(subj, body, recId);
    }
}