src/objects/ProjectFieldDisplay__c.object
<CustomObject>
    <fields>
        <fullName>ProjectRecordTypeId__c</fullName>
        <description>1. Full EPC
2. Install Only
3. Partial EPC
4. Remove/Replace
5. Exception Project
6. Utility Program</description>
        <inlineHelpText>Choose the Record Type(s) that this Project Field Display should be associated with. Multiple selections are allowed on an single Project Field Display record, but any individual Record Type may only be chosen once across all Project Field Display records</inlineHelpText>
        <label>Project Record Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>012610000001sUdAAI</fullName>
                </value>
                <value>
                    <fullName>012610000001sUiAAI</fullName>
                </value>
                <value>
                    <fullName>01261000000kpsMAAQ</fullName>
                </value>
                <value>
                    <fullName>01261000000MCV2AAO</fullName>
                </value>
                <value>
                    <fullName>01261000000krSiAAI</fullName>
                </value>
                <value>
                    <fullName>01261000000ksKIAAY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section1Label__c</fullName>
        <label>Section 1 Label</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section1Order__c</fullName>
        <label>Section 1 Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section1Tab__c</fullName>
        <label>Section 1 Tab</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section1__c</fullName>
        <description>API Field names, comma delimited. BLANK will set a blank space on the Project Details view</description>
        <label>Section 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project Field Display</label>
    <nameField>
        <label>Project Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Field Displays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestProjectDetail.cls
@isTest
private class TestProjectDetail {
	
    @isTest static void test_method_one() {
		
        TestDataUtility.CreateData();
        if (TestDataUtility.dataCreated) {
        
        	// create pfd rec
        	ProjectFieldDisplay__c p = new ProjectFieldDisplay__c();
        	p.name = 'Install Only';
        	p.ProjectRecordTypeId__c =TestDataUtility.utilOpportunities[0].RecordTypeId;
        	p.Section1Label__c = 'Project Info';
        	p.Section1Tab__c = 'Project Info';
        	p.Section1__c = 'name;recordtypeid;BLANK;accountid';
                p.Section1Order__c = 1;
        	insert p;
	
        	// start functionality/coverage testing
        	// instantiate controller
        	ProjectDetail pd = new ProjectDetail();
        	
        	// populate required info
        	pd.TabName = 'Project Info';
        	pd.RecordId = TestDataUtility.utilOpportunities[0].Id;
        	pd.RTypeId = TestDataUtility.utilOpportunities[0].RecordTypeId;
        	
        	// coverage
        	pd.editMode = false;
        	pd.ReloadMainPage = false;
        	string s = pd.ReloadURL;
        	
        	// test bulk of field gathering and query building
        	boolean test = pd.isMapEmpty;
        	system.debug('before assert: ' + test);
        	// make sure the field map isn't empty
        	system.assert(!test);
	
        	// test opp query builder and query
        	Opportunity o = pd.TheProject;
        	// make sure the opp gathered in the class matches the opp created here
        	system.assertEquals(TestDataUtility.utilOpportunities[0].Id, o.id);
	
        	// action tests
        	// edit mode test
        	pd.goEdit();
        	// make sure edit mode was activated
        	system.assert(pd.editMode);
        	
        	pd.Cancel();
        	// make sure edit mode was deactivated
        	system.assert(!pd.editMode);
	
        	// switch record type
        	RecordType rt4 = [SELECT id,Name 
        	                         FROM RecordType 
        	                         WHERE SobjectType='opportunity' AND Name='Partial EPC'];
	
        	pd.TheProject.RecordTypeId = rt4.Id;
        	pd.Save();
        	// test that the op in the class was updated
        	system.assertNotEquals(TestDataUtility.utilOpportunities[0].RecordTypeId, pd.TheProject.RecordTypeId);
        	Opportunity reopp = [SELECT id, RecordTypeId FROM Opportunity WHERE id = :TestDataUtility.utilOpportunities[0].Id];
        	system.assertEquals(reopp.RecordTypeId, pd.TheProject.RecordTypeId);

            pd.editModeCancel();
            pd.editModeSave();
        }
	}
		
}